config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  
  resources :articles
  
  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def new
    
  end
  
  def create
    
  end
  
  def edit
    
  end
  
  def show
    
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/new.html.erb
<%= form_for :article, url: articles_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/_footer.html.erb
<footer>Copyrights By RootKaro since @2015</footer>

app/views/layouts/_header.html.erb
<header>
  <h1 class="heading"><%= link_to "RootKaro", welcome_index_url %></h1>
  <h2 class="subtitle">Do Customization By Yourself</h2>
</header>

app/views/layouts/_sidebar.html.erb
<div class="main-sidebar">
  <div class="sidebar">
    <div class="user-panel">
      <div class="pull-left image">
        <img alt="User Image" class="user-image" src="http://placehold.it/160x160" />
      </div>
      <div class="pull-left info">
        <p>
          User Name
        </p>
        <a href="#">
          <i class="fa fa-circle text-success">
          </i>Online
          </a>
      </div>
    </div>
    <form action="#" class="sidebar-form" method="get">
      <div class="input-group">
        <input class="form-control" name="q" placeholder="Search..." type="text" />
        <span class="input-group-btn">
        <button class="btn btn-flat" id="search-btn" name="search" type="submit">
        <i class="fa fa-search">
        </i></button></span>
      </div>
    </form>
    <ul class="sidebar-menu">
      <li class="header">
        HEADER
      </li>
      <li class="active">
        <a href="#">
      <span>Link</span>
      </a>
      </li>
      <li>
        <a href="#">
        <span>Another Link</span>
        </a>
      </li>
      <li class="treeview">
        <a href="#">
          <span>Multilevel</span>
          <i class="fa fa-angle-left pull-right">
          </i></a>
        <ul class="treeview-menu">
          <li>
            <a href="#"> Link in level 2</a>
          </li>
          <li>
            <a href="#"> Link in level 2</a>
          </li>
        </ul>
      </li>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= render "layouts/sidebar" %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/welcome/index.html.erb
<marquee>
  <h1>Welcome to rails !!!</h1>
</marquee>